FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN cd packages/client && npx vite build

FROM nginx:alpine
COPY --from=build /app/packages/client/dist /usr/share/nginx/html
EXPOSE 8080
RUN sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/conf.d/default.conf
